#!/usr/bin/env bash

# get volume levels (left right)
volume=$(amixer get Master | grep -oP '\[\d+%\]' | tr -d '[]%')
read -r number _ <<< "$volume" # get the first number (left volume)
volume=$((number)) # convert to integer

# check if muted
mute=$(amixer get Master | grep -oP '\[on\]|\[off\]' | head -1)

# change icon based on volume level
if [ "$mute" == "[off]" ]; then
    icon=" "
elif [ "$volume" -eq 0 ]; then
    icon=" "
elif [ "$volume" -le 30 ]; then
    icon=" "
elif [ "$volume" -le 100 ]; then
    icon=" "
fi

# display output
echo "$icon $volume%"
echo ""

# color red if muted
if [ "$mute" == "[off]" ]; then
    echo "#FF0000"
fi
